FROM php:8.1-apache

# Installer les dépendances PHP et les outils nécessaires
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copier les fichiers de votre application dans le conteneur
COPY ./backend /var/www/html

# Configurer les permissions et les dossiers
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# Activer les modules Apache nécessaires
RUN a2enmod rewrite

# Exposer le port 80
EXPOSE 80

# Démarrer Apache
CMD ["apache2-foreground"]
