# Dockerfile.multi
FROM ubuntu:latest

# Installez Docker CLI
RUN apt-get update && apt-get install -y \
    docker.io \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copiez le script de construction personnalisé dans le conteneur
COPY build.sh /build.sh

# Rendre le script exécutable
RUN chmod +x /build.sh

# Commande d'entrée pour exécuter le script
ENTRYPOINT ["/build.sh"]
